---
galaxy_info:
  role_name: vmware_vsphere
  namespace: default
  author: Dirk Egert
  description: Role to manage vmware_vsphere
  company: degert-it.de
  license: license (BSD, MIT)
  min_ansible_version: '2.8'
  galaxy_tags: []
dependencies: []
