---
- name: Ensure all needed vars are present
  ansible.builtin.include_tasks: assert.yml
  tags:
    - always

- name: Fetch vSphere username from Vault or fallback
  ansible.builtin.set_fact:
    vvs_username: >-
      {{ lookup('community.hashi_vault.hashi_vault', vvs_vmware_username_lookup, default=vvs_username) }}
  tags:
    - always

- name: Fetch vSphere password from Vault or fallback
  ansible.builtin.set_fact:
    vvs_password: >-
      {{ lookup('community.hashi_vault.hashi_vault', vvs_vmware_password_lookup, default=vvs_password) }}
  no_log: true
  tags:
    - always

- name: Create VM folder
  ansible.builtin.include_tasks: create_vm_folder.yml
  when: not vvs_destroy | bool
  tags:
    - create_vm_folder

- name: Create VMs
  ansible.builtin.include_tasks: create_vm.yml
  when: not vvs_destroy | bool
  tags:
    - create_vms

- name: Destroy VMs
  ansible.builtin.include_tasks: destroy_vm.yml
  when: vvs_destroy | bool
  tags:
    - destroy_vms
    - destroy_all

- name: Destroy VM folder
  ansible.builtin.include_tasks: destroy_vm_folder.yml
  when: vvs_destroy | bool
  tags:
    - destroy_vm_folder
    - destroy_all
