---
ocp_manage_operator_api_version: v1
ocp_manage_operator_approve: true
ocp_manage_operator_channel: stable
ocp_manage_operator_create_namespace: false
ocp_manage_operator_deployment_name: ''
ocp_manage_operator_name: rhsso-operator
ocp_manage_operator_namespace: rhsso
ocp_manage_operator_group_name: "{{ ocp_manage_operator_name }}-group"
ocp_manage_operator_plan: Manual
ocp_manage_operator_source: redhat-operators
ocp_manage_operator_source_namespace: openshift-marketplace
ocp_manage_operator_starting_csv: ''
ocp_manage_operator_project_metadata_extras: ''
ocp_manage_operator_subscription_extras: ''
ocp_manage_operator_state: present
ocp_manage_operator_target_namespaces: false
