---
galaxy_info:
  role_name: gitops
  namespace: default
  author: Dirk Egert
  description: Role to manage gitops Installation
  company: degert-it.de
  license: license (BSD, MIT)
  min_ansible_version: '2.8'
  galaxy_tags: []
dependencies: []
