---
- name: Create necessary directories
  delegate_to: "{{ ins_delegate_to }}"
  run_once: true
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: "0775"
    recurse: true
  loop: "{{ ins_cluster_sub_dirs | dict2items }}"
  tags:
    - always

- name: Create a directory ~/.docker
  delegate_to: "{{ ins_delegate_to }}"
  run_once: true
  ansible.builtin.file:
    path: "$HOME/.docker/"
    state: directory
    mode: '0700'
  tags:
    - always

- name: Create ~/.docker/config.json
  delegate_to: "{{ ins_delegate_to }}"
  run_once: true
  ansible.builtin.copy:
    content: "{{ ins_pullsecret }}"
    # content: "{{ ins_pullsecret | replace(\"'\", '') }}"
    dest: "$HOME/.docker/config.json"
    mode: '0644'
  tags:
    - always

- name: Download oc client tools
  delegate_to: "{{ ins_delegate_to }}"
  run_once: true
  ansible.builtin.get_url:
    url: "{{ ins_occlient }}"
    dest: "{{ ins_cluster_sub_dirs.download }}"
    mode: '0644'

- name: Unarchive ocp tools
  delegate_to: "{{ ins_delegate_to }}"
  run_once: true
  environment:
    no_proxy: "{{ ins_no_proxy | default('', true) }}"
    http_proxy: "{{ ins_proxy_url | default('', true) }}"
    https_proxy: "{{ ins_proxy_url | default('', true) }}"
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ ins_cluster_sub_dirs.bin }}"
    remote_src: true
  vars:
    _ins_occlient_file: "{{ ins_cluster_sub_dirs.download }}/{{ ins_occlient | basename }}"
  loop:
    - "{{ _ins_occlient_file }}"
  changed_when: false

- name: Extract openshift-install
  delegate_to: "{{ ins_delegate_to }}"
  run_once: true
  environment:
    no_proxy: "{{ ins_no_proxy | default('', true) }}"
    http_proxy: "{{ ins_proxy_url | default('', true) }}"
    https_proxy: "{{ ins_proxy_url | default('', true) }}"
  ansible.builtin.command:
    cmd: >-
      {{ ins_cluster_sub_dirs.bin }}/oc adm release extract --command="openshift-install"
      --command-os="{{ ins_os }}" "{{ ins_download_url }}:{{ ins_version }}-{{ ins_arch }}"
      --to="{{ ins_cluster_sub_dirs.download }}/" --registry-config="$HOME/.docker/config.json"
  register: openshift_install
  changed_when: openshift_install.rc == 0
  tags: extract_ins_install
